# Evaluation config for Qwen3-VL on the M2SV dataset

model:
  model_name: "Qwen/Qwen3-VL-8B-Instruct"
  dtype: "float16"
  device_map: "auto"

dataset:
  name: "yosubshin/m2sv"
  split: "train"

generation:
  max_new_tokens: 4096
  temperature: 0.1
  limit:

output:
  dir: "./eval_results/qwen3_vl_8b_instruct_m2sv_20251017_v2"
  save_predictions: true
