# Evaluation config for Qwen3-VL on the M2SV dataset

model:
  model_name: "Qwen/Qwen3-VL-30B-A3B-Instruct"
  dtype: "float16"
  device_map: "auto"

dataset:
  name: "yosubshin/m2sv"
  split: "validation"

generation:
  max_new_tokens: 4096
  temperature: 0.1
  limit:

output:
  dir: "./eval_results/qwen3_vl_30b_a3b_instruct_m2sv_20251017_v2"
  save_predictions: true

inference:
  backend: vllm
  vllm:
    # api_base: "http://127.0.0.1:8000"
    # api_key: "EMPTY"
    # model: "Qwen/Qwen3-VL-30B-A3B-Instruct"
    max_concurrency: 8
    request_timeout_s: 120
    max_retries: 3
